theme: jekyll-theme-minimal
title: Mohammad Sefid
description: Communication Systems Graduated of master's from Electrical and Computer engineering faculty Khaje Nasir University of Technology KNTU in Tehran, Iran 
