theme: jekyll-theme-slate
title: Mohammad Sefid
description: Communication Systems Graduate of Master's in Electrical and Electronics Engineering (EE), Khaje Nasir Toosi University of Technology (KNTU), Tehran, Iran
