theme: jekyll-theme-minimal
title: Mohammad Sefid
<p style="color: lightblue;"> description: Communication Systems Graduated of master's from Electrical and Electronics engineering (EE) faculty Khaje Nasir University of Technology KNTU in Tehran, Iran </p>
